### ISSUE TITLE
Investigate Umlaut escaping

### ISSUE THREAD

**Issue by ApolloLV** [ApolloLV/flunkysimulator#82]
Since we started using HTML escaping on the server side, player names with Umlauts are not working.

**Comment by stheid** [comment]
could be solved on client side with #84 being solved, but otherwise there is no way to match the current player with the button assigned to it, because the buttons are generated and feed through states from the server (escaped) while the internal javascript variable is feed by the user.

if the internal javascript variable is also feed by the server it could be solved.

# remaining problems
the escapes would still be printed literally in the chat window.

**Comment by stheid** [comment]
fortunately #83 solved most of the issues, meaning that umlaut players can be removed and moved.

The only remaining problem in the current state:
- reclaiming username is not possible with umlauts

**Comment by stheid** [comment]
The investigation is finished and need to be implemented in #84 and #93
